language: go
sudo: false
go:
  - 1.7
  - 1.8
  - master
before_install:
  - curl https://glide.sh/get | sh
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/mattn/goveralls
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - glide install
script:
  - gometalinter --config=gometalinter.json --deadline=600s ./...
  - rm -f coverage.*
  - "touch coverage.tmp && echo 'mode: atomic' > coverage.txt && go list ./... | grep -v \"/vendor/\" | xargs -n1 -I{} sh -c 'go test -covermode=atomic -coverprofile=coverage.tmp {} && tail -n +2 coverage.tmp >> coverage.txt' && rm coverage.tmp"
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.txt -service=travis-ci -repotoken $COVERALLS_TOKEN
